"""adding further gsmodel relation tables

Revision ID: 07c3f01b8866
Revises: 4c453ef512e4
Create Date: 2020-10-29 20:43:46.740399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c3f01b8866'
down_revision = '4c453ef512e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gsmodelapp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['id'], ['gsmodelbase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gsmodelnet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('net_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['gsmodelbase.id'], ),
    sa.ForeignKeyConstraint(['net_id'], ['network.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gsmodelroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['gsmodelbase.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gsmodelsys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sys_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['gsmodelbase.id'], ),
    sa.ForeignKeyConstraint(['sys_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gsmodelsys')
    op.drop_table('gsmodelroom')
    op.drop_table('gsmodelnet')
    op.drop_table('gsmodelapp')
    # ### end Alembic commands ###
