"""Grundschutz Kompendium tables

Revision ID: 16e1a1fcdacd
Revises: 306588cf62b3
Create Date: 2020-10-26 20:37:43.832139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e1a1fcdacd'
down_revision = '306588cf62b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogue_name'), 'catalogue', ['name'], unique=False)
    op.create_table('threat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_name'), 'threat', ['name'], unique=False)
    op.create_table('buildingblockgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shorthand', sa.String(length=4), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('catalogue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildingblockgroup_name'), 'buildingblockgroup', ['name'], unique=False)
    op.create_index(op.f('ix_buildingblockgroup_shorthand'), 'buildingblockgroup', ['shorthand'], unique=False)
    op.create_table('buildingblock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prio', sa.Enum('R1', 'R2', 'R3', name='implementationpriority'), nullable=True),
    sa.Column('order', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('buildingblockgroup_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buildingblockgroup_id'], ['buildingblockgroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildingblock_name'), 'buildingblock', ['name'], unique=False)
    op.create_table('requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protection_level', sa.Enum('BASE', 'STANDARD', 'HIGH', name='protectionlevel'), nullable=True),
    sa.Column('order', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('buildingblock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['buildingblock_id'], ['buildingblock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_name'), 'requirement', ['name'], unique=False)
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirement_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_name'), 'action', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_name'), table_name='action')
    op.drop_table('action')
    op.drop_index(op.f('ix_requirement_name'), table_name='requirement')
    op.drop_table('requirement')
    op.drop_index(op.f('ix_buildingblock_name'), table_name='buildingblock')
    op.drop_table('buildingblock')
    op.drop_index(op.f('ix_buildingblockgroup_shorthand'), table_name='buildingblockgroup')
    op.drop_index(op.f('ix_buildingblockgroup_name'), table_name='buildingblockgroup')
    op.drop_table('buildingblockgroup')
    op.drop_index(op.f('ix_threat_name'), table_name='threat')
    op.drop_table('threat')
    op.drop_index(op.f('ix_catalogue_name'), table_name='catalogue')
    op.drop_table('catalogue')
    # ### end Alembic commands ###
