"""removing level from BB

Revision ID: 1e5c68b75c13
Revises: 2669f1dbd938
Create Date: 2020-10-27 15:51:36.123474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e5c68b75c13'
down_revision = '2669f1dbd938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildingblock', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildingblock', sa.Column('level', mysql.ENUM('BASE', 'STANDARD', 'HIGH'), nullable=True))
    # ### end Alembic commands ###
