"""adding column number to System

Revision ID: 2bf3fd454caf
Revises: 4eff8f9d8b63
Create Date: 2020-10-29 08:00:12.352670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bf3fd454caf'
down_revision = '4eff8f9d8b63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system', 'number')
    # ### end Alembic commands ###
