"""adding column is_external to Network

Revision ID: 4eff8f9d8b63
Revises: 5bcca0ac23da
Create Date: 2020-10-28 22:18:44.816896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eff8f9d8b63'
down_revision = '5bcca0ac23da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network', sa.Column('is_external', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('network', 'is_external')
    # ### end Alembic commands ###
