"""adding dom_id to gsmodel base relation table

Revision ID: 5a0a0d011948
Revises: 07c3f01b8866
Create Date: 2020-10-29 21:04:00.842211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a0a0d011948'
down_revision = '07c3f01b8866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsmodelbase', sa.Column('dom_id', sa.Integer(), nullable=False))
    op.alter_column('gsmodelbase', 'bb_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'gsmodelbase', 'infodomain', ['dom_id'], ['id'])
    op.drop_constraint('gsmodeldom_ibfk_1', 'gsmodeldom', type_='foreignkey')
    op.drop_column('gsmodeldom', 'dom_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsmodeldom', sa.Column('dom_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('gsmodeldom_ibfk_1', 'gsmodeldom', 'infodomain', ['dom_id'], ['id'])
    op.drop_constraint(None, 'gsmodelbase', type_='foreignkey')
    op.alter_column('gsmodelbase', 'bb_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('gsmodelbase', 'dom_id')
    # ### end Alembic commands ###
