"""implementing various associations

Revision ID: 5bcca0ac23da
Revises: f13900e7cc89
Create Date: 2020-10-28 09:57:50.226545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcca0ac23da'
down_revision = 'f13900e7cc89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_app_sys',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'system_id')
    )
    op.create_table('association_sys_net',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['network.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('system_id', 'network_id')
    )
    op.create_table('association_sys_room',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('system_id', 'room_id')
    )
    op.create_table('association_proc_app',
    sa.Column('coreprocess_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.id'], ),
    sa.ForeignKeyConstraint(['coreprocess_id'], ['coreprocess.id'], ),
    sa.PrimaryKeyConstraint('coreprocess_id', 'application_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_proc_app')
    op.drop_table('association_sys_room')
    op.drop_table('association_sys_net')
    op.drop_table('association_app_sys')
    # ### end Alembic commands ###
