"""remodelling gsmodel, adding checklists

Revision ID: 5ca53d33f91b
Revises: 3f7e31ac02c1
Create Date: 2020-11-02 15:28:46.298352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ca53d33f91b'
down_revision = '3f7e31ac02c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('gsmodelbase_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['gsmodelbase_id'], ['gsmodelbase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checklist_name'), 'checklist', ['name'], unique=False)
    op.drop_constraint('gsmodelbase_ibfk_2', 'gsmodelbase', type_='foreignkey')
    op.drop_column('gsmodelbase', 'implementation_decision')
    op.drop_column('gsmodelbase', 'est_amount')
    op.drop_column('gsmodelbase', 'responsible')
    op.drop_column('gsmodelbase', 'implementation_status')
    op.drop_column('gsmodelbase', 'comments')
    op.drop_column('gsmodelbase', 'target_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gsmodelbase', sa.Column('target_date', sa.DATE(), nullable=True))
    op.add_column('gsmodelbase', sa.Column('comments', mysql.TEXT(), nullable=True))
    op.add_column('gsmodelbase', sa.Column('implementation_status', mysql.ENUM('OPEN', 'WIP', 'DONE'), nullable=True))
    op.add_column('gsmodelbase', sa.Column('responsible', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('gsmodelbase', sa.Column('est_amount', mysql.FLOAT(), nullable=True))
    op.add_column('gsmodelbase', sa.Column('implementation_decision', mysql.ENUM('NA', 'YES', 'PART', 'NO'), nullable=True))
    op.create_foreign_key('gsmodelbase_ibfk_2', 'gsmodelbase', 'person', ['responsible'], ['id'])
    op.drop_index(op.f('ix_checklist_name'), table_name='checklist')
    op.drop_table('checklist')
    # ### end Alembic commands ###
