"""adding infodomain relation to checklists

Revision ID: 7afdef308831
Revises: 5ca53d33f91b
Create Date: 2020-11-02 15:42:55.514539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afdef308831'
down_revision = '5ca53d33f91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist', sa.Column('infodomain_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'checklist', 'infodomain', ['infodomain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checklist', type_='foreignkey')
    op.drop_column('checklist', 'infodomain_id')
    # ### end Alembic commands ###
