"""Extending Coreprocess class

Revision ID: 8a34d1fd1026
Revises: 4749cb722797
Create Date: 2020-10-26 11:02:35.519831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a34d1fd1026'
down_revision = '4749cb722797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coreprocess', sa.Column('responsible', sa.Integer(), nullable=True))
    op.add_column('coreprocess', sa.Column('type', sa.Enum('CORE', 'SUPPORTING', name='processtype'), nullable=True))
    op.add_column('coreprocess', sa.Column('user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coreprocess', 'person', ['responsible'], ['id'])
    op.create_foreign_key(None, 'coreprocess', 'person', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coreprocess', type_='foreignkey')
    op.drop_constraint(None, 'coreprocess', type_='foreignkey')
    op.drop_column('coreprocess', 'user')
    op.drop_column('coreprocess', 'type')
    op.drop_column('coreprocess', 'responsible')
    # ### end Alembic commands ###
