"""adding column is_active to BuildingBlock

Revision ID: e44c7850c9fb
Revises: 2bf3fd454caf
Create Date: 2020-10-29 09:25:52.405286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44c7850c9fb'
down_revision = '2bf3fd454caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildingblock', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildingblock', 'is_active')
    # ### end Alembic commands ###
