"""adding order to requirement again...

Revision ID: f13900e7cc89
Revises: f66600454845
Create Date: 2020-10-27 17:53:07.103962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13900e7cc89'
down_revision = 'f66600454845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirement', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirement', 'order')
    # ### end Alembic commands ###
